
(function(){
'use strict';
const n=v=>Number(v||0);
function migrate(c){
 const d=c.db;d.meta=d.meta||{};d.meta.version=Math.max(Number(d.meta.version||1),7);d.meta.savedAt=Number(d.meta.savedAt||Date.now());
 ['productVariants','uomConversions','transferOrders','bulkCounts','coupons','exchanges','purchaseRequests','rfqs','vendorBills','vendorCredits','supplierPriceHistory','openingBalances','fiscalYears','fiscalPeriods','costCenters','documentTemplates','importJobs','runtimeChecks'].forEach(k=>d[k]=d[k]||[]);
 d.settings=d.settings||{};d.settings.thermalWidth=d.settings.thermalWidth||'80';d.settings.barcodeLabelSize=d.settings.barcodeLabelSize||'50x30';
 (d.products||[]).forEach(p=>Object.assign(p,{baseUom:p.baseUom||p.unit||'قطعة',uoms:p.uoms||[p.unit||'قطعة']}));
 if(!d.accounts.some(a=>a.code==='3000'))d.accounts.push({id:'a-3000',code:'3000',name:'حقوق الملكية',type:'equity'});
 if(!d.accounts.some(a=>a.code==='3100'))d.accounts.push({id:'a-3100',code:'3100',name:'أرصدة افتتاحية',type:'equity'});
 if(!d.fiscalYears.length){const y=new Date().getFullYear();d.fiscalYears.push({id:'fy-'+y,name:String(y),from:y+'-01-01',to:y+'-12-31',status:'open'});for(let m=1;m<=12;m++){const mm=String(m).padStart(2,'0'),last=new Date(y,m,0).getDate();d.fiscalPeriods.push({id:'fp-'+y+'-'+mm,yearId:'fy-'+y,name:y+'-'+mm,from:y+'-'+mm+'-01',to:y+'-'+mm+'-'+last,status:'open'})}}
}
function uniq(prefix,arr){let i=1,v;const set=new Set((arr||[]).map(x=>String(x.number||'')));do{v=prefix+'-'+String(i++).padStart(5,'0')}while(set.has(v));return v}
const prod=(c,id)=>c.db.products.find(x=>x.id===id);
const wh=(c,id)=>c.db.warehouses.find(x=>x.id===id);
function variants(c,pid){return c.db.productVariants.filter(x=>x.productId===pid&&x.active!==false)}
function uomFactor(c,pid,uom){const p=prod(c,pid);if(!p||!uom||uom===p.baseUom)return 1;return n(c.db.uomConversions.find(x=>x.productId===pid&&x.uom===uom)?.factor||1)}
function inTransit(c,pid,wid){return c.db.transferOrders.filter(t=>t.status==='in_transit'&&t.productId===pid&&(t.from===wid||t.to===wid)).reduce((s,t)=>s+(t.to===wid?n(t.qty):-n(t.qty)),0)}
function variantStock(c,id,wid){return c.db.stockMoves.filter(m=>m.variantId===id&&(!wid||m.warehouseId===wid)).reduce((s,m)=>s+(['delivery','out','return_supplier'].includes(m.type)?-n(m.qty):n(m.qty)),0)}

function viewProducts(c){
 const base=NBHYPER.viewProducts(c),vs=c.db.productVariants.filter(x=>x.companyId===c.db.session.companyId),us=c.db.uomConversions.filter(x=>x.companyId===c.db.session.companyId);
 return base+`<div class="pr-grid2"><section class="card"><div class="card-head"><h3>Variants حقيقية</h3><button class="btn sm" id="newVariant">＋ Variant</button></div>${vs.slice(-15).reverse().map(v=>`<div class="stat-row"><div class="grow"><strong>${c.esc(prod(c,v.productId)?.nameAr||'')} • ${c.esc(v.name)}</strong><div class="sub">${c.esc(v.sku)} • مخزون ${variantStock(c,v.id,c.warehouse()?.id)}</div></div><strong>${c.fmt(v.price||prod(c,v.productId)?.price||0)}</strong></div>`).join('')||'<div class="empty">لا توجد متغيرات</div>'}</section><section class="card"><div class="card-head"><h3>وحدات القياس</h3><button class="btn sm" id="newUom">＋ تحويل</button></div>${us.slice(-15).reverse().map(x=>`<div class="stat-row"><div class="grow"><strong>${c.esc(prod(c,x.productId)?.nameAr||'')}</strong><div class="sub">1 ${c.esc(x.uom)} = ${x.factor} ${c.esc(prod(c,x.productId)?.baseUom||'قطعة')}</div></div></div>`).join('')||'<div class="empty">لا توجد تحويلات</div>'}</section></div><div class="card"><div class="card-head"><h3>Barcode Labels</h3><button class="btn outline" id="printLabels">طباعة ملصقات</button></div><div class="sub">اسم المنتج + السعر + SKU/Barcode بتنسيق ملصقات للمخزن.</div></div>`;
}
function variantForm(c){return `<form id="variantForm"><div class="form-grid"><div class="field"><label>المنتج</label><select name="productId">${c.db.products.filter(p=>p.active).map(p=>`<option value="${p.id}">${c.esc(p.nameAr)}</option>`).join('')}</select></div><div class="field"><label>اسم المتغير</label><input name="name" required></div><div class="field"><label>SKU</label><input name="sku" required></div><div class="field"><label>Barcode</label><input name="barcode"></div><div class="field"><label>السعر</label><input name="price" type="number" min="0"></div><div class="field"><label>التكلفة</label><input name="cost" type="number" min="0"></div></div><div class="toolbar"><button class="btn primary">حفظ</button><button type="button" class="btn" data-close>إلغاء</button></div></form>`}
function uomForm(c){return `<form id="uomForm"><div class="form-grid"><div class="field"><label>المنتج</label><select name="productId">${c.db.products.filter(p=>p.active).map(p=>`<option value="${p.id}">${c.esc(p.nameAr)}</option>`).join('')}</select></div><div class="field"><label>الوحدة</label><input name="uom" placeholder="كرتون / درزن" required></div><div class="field"><label>كم تساوي من الوحدة الأساسية</label><input name="factor" type="number" min=".0001" step=".0001" required></div></div><div class="toolbar"><button class="btn primary">حفظ</button><button type="button" class="btn" data-close>إلغاء</button></div></form>`}
function wireProducts(c){
 NBHYPER.wireProducts(c);
 document.querySelector('#newVariant')?.addEventListener('click',()=>{c.openModal('Variant جديد',variantForm(c),false);setTimeout(()=>{const f=document.querySelector('#variantForm');if(f)f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),sku=String(fd.get('sku')||'').trim();if(c.db.productVariants.some(v=>v.sku===sku)||c.db.products.some(p=>p.sku===sku)){c.toast('SKU مستخدم مسبقاً');return}c.db.productVariants.push({id:c.uid('var'),companyId:c.db.session.companyId,productId:fd.get('productId'),name:fd.get('name'),sku,barcode:fd.get('barcode'),price:n(fd.get('price')),cost:n(fd.get('cost')),active:true,createdAt:c.now()});c.audit('إنشاء Variant','Product',sku);c.save('تم حفظ Variant');c.closeModal();c.render()}},0)});
 document.querySelector('#newUom')?.addEventListener('click',()=>{c.openModal('تحويل وحدة',uomForm(c),false);setTimeout(()=>{const f=document.querySelector('#uomForm');if(f)f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),pid=fd.get('productId'),u=String(fd.get('uom')||'').trim();c.db.uomConversions=c.db.uomConversions.filter(x=>!(x.productId===pid&&x.uom===u));c.db.uomConversions.push({id:c.uid('uom'),companyId:c.db.session.companyId,productId:pid,uom:u,factor:n(fd.get('factor'))||1});const p=prod(c,pid);p.uoms=[...new Set([...(p.uoms||[]),u])];c.save('تم حفظ التحويل');c.closeModal();c.render()}},0)});
 document.querySelector('#printLabels')?.addEventListener('click',()=>printLabels(c))
}
function printLabels(c){
 const q=prompt('اكتب SKU مفصولة بفاصلة أو اتركه فارغاً لأول 20 منتج',''),want=(q||'').split(',').map(x=>x.trim()).filter(Boolean),arr=(want.length?c.db.products.filter(p=>want.includes(p.sku)):c.db.products.slice(0,20));if(!arr.length)return c.toast('لا توجد منتجات');const w=window.open('','_blank');if(!w)return c.toast('اسمح بالنوافذ المنبثقة');w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><style>@page{margin:3mm}body{font-family:Arial;display:grid;grid-template-columns:repeat(3,50mm);gap:2mm}.l{width:50mm;height:30mm;border:1px solid #bbb;padding:3mm;box-sizing:border-box;text-align:center}.l b,.l small{display:block;margin:2px}</style></head><body>${arr.map(p=>`<div class="l"><strong>${c.esc(p.nameAr)}</strong><b>${c.fmt(p.price)}</b><small>${c.esc(p.barcode||p.sku)}</small></div>`).join('')}<script>onload=()=>print()<\/script></body></html>`);w.document.close()
}

function viewInventory(c){
 const base=NBADV.viewInventory(c),ts=c.db.transferOrders.filter(x=>x.companyId===c.db.session.companyId),lots=c.db.lots.filter(x=>x.expiry&&x.expiry>=c.today()).sort((a,b)=>a.expiry.localeCompare(b.expiry));
 return base+`<div class="pr-grid2"><section class="card"><div class="card-head"><h3>Available / Reserved / In Transit</h3><button class="btn sm" id="newTransit">＋ تحويل مرحلي</button></div>${c.db.products.filter(p=>p.trackStock&&p.active).slice(0,15).map(p=>{const w=c.warehouse()?.id,avail=NBADV.availableStock(c,p.id,w),res=NBADV.reservedQty(c,p.id,w),tr=inTransit(c,p.id,w);return`<div class="pr-stock-row"><strong>${c.esc(p.nameAr)}</strong><span>متاح ${avail}</span><span>محجوز ${res}</span><span>بالطريق ${tr}</span></div>`}).join('')}</section><section class="card"><div class="card-head"><h3>التحويلات</h3><button class="btn sm" id="bulkCount">جرد جماعي</button></div>${ts.slice(-12).reverse().map(t=>`<div class="stat-row"><div class="grow"><strong>${c.esc(t.number)} • ${c.esc(prod(c,t.productId)?.nameAr||'')}</strong><div class="sub">${c.esc(wh(c,t.from)?.name||'')} ← ${c.esc(wh(c,t.to)?.name||'')} • ${t.qty}</div></div><span class="badge ${t.status==='received'?'green':t.status==='in_transit'?'purple':'gray'}">${c.esc(t.status)}</span>${t.status==='draft'?`<button class="btn sm" data-send-transfer="${t.id}">إرسال</button>`:''}${t.status==='in_transit'?`<button class="btn sm green" data-receive-transfer="${t.id}">استلام</button>`:''}</div>`).join('')||'<div class="empty">لا توجد تحويلات</div>'}<div class="card-head"><h3>أقرب صلاحيات</h3></div>${lots.slice(0,8).map(l=>`<div class="stat-row"><div class="grow"><strong>${c.esc(prod(c,l.productId)?.nameAr||'')} • ${c.esc(l.code)}</strong><div class="sub">${l.expiry}</div></div><strong>${l.qty}</strong></div>`).join('')||'<div class="empty">لا توجد بيانات</div>'}</section></div>`;
}
function transferForm(c){const ws=c.db.warehouses.filter(w=>w.companyId===c.db.session.companyId);return `<form id="transitForm"><div class="form-grid"><div class="field"><label>من</label><select name="from">${ws.map(w=>`<option value="${w.id}">${c.esc(w.name)}</option>`).join('')}</select></div><div class="field"><label>إلى</label><select name="to">${ws.map(w=>`<option value="${w.id}">${c.esc(w.name)}</option>`).join('')}</select></div><div class="field"><label>المنتج</label><select name="productId">${c.db.products.filter(p=>p.trackStock&&p.active).map(p=>`<option value="${p.id}">${c.esc(p.nameAr)}</option>`).join('')}</select></div><div class="field"><label>الكمية</label><input name="qty" type="number" min=".01" step=".01" required></div></div><div class="toolbar"><button class="btn primary">إنشاء</button><button class="btn" type="button" data-close>إلغاء</button></div></form>`}
function bulkForm(c){const wid=c.warehouse()?.id||'',ps=c.db.products.filter(p=>p.trackStock&&p.active).slice(0,80);return `<form id="bulkCountForm"><div class="field"><label>المخزن</label><select name="warehouseId">${c.db.warehouses.filter(w=>w.companyId===c.db.session.companyId).map(w=>`<option value="${w.id}" ${w.id===wid?'selected':''}>${c.esc(w.name)}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>المنتج</th><th>النظام</th><th>الفعلي</th></tr></thead><tbody>${ps.map(p=>`<tr data-pid="${p.id}"><td>${c.esc(p.nameAr)}</td><td>${c.stock(p.id,wid)}</td><td><input class="actual" type="number" min="0" step=".01"></td></tr>`).join('')}</tbody></table></div><div class="toolbar"><button class="btn primary">تطبيق</button><button class="btn" type="button" data-close>إلغاء</button></div></form>`}
function wireInventory(c){
 NBADV.wireInventory(c);
 document.querySelector('#newTransit')?.addEventListener('click',()=>{c.openModal('تحويل مرحلي',transferForm(c),false);setTimeout(()=>{const f=document.querySelector('#transitForm');if(f)f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),from=fd.get('from'),to=fd.get('to'),pid=fd.get('productId'),qty=n(fd.get('qty'));if(from===to)return c.toast('اختر مخزنين مختلفين');if(NBADV.availableStock(c,pid,from)<qty)return c.toast('الكمية غير متاحة');const x={id:c.uid('tr'),companyId:c.db.session.companyId,number:uniq('TR',c.db.transferOrders),from,to,productId:pid,qty,status:'draft',createdAt:c.now()};c.db.transferOrders.unshift(x);c.save('تم إنشاء '+x.number);c.closeModal();c.render()}},0)});
 document.querySelectorAll('[data-send-transfer]').forEach(b=>b.onclick=()=>{const x=c.db.transferOrders.find(t=>t.id===b.dataset.sendTransfer);if(!x)return;if(NBADV.availableStock(c,x.productId,x.from)<x.qty)return c.toast('المخزون غير كافٍ');c.db.stockMoves.push({id:c.uid('sm'),companyId:x.companyId,warehouseId:x.from,productId:x.productId,type:'out',qty:x.qty,date:c.today(),ref:x.number,note:'قيد النقل'});x.status='in_transit';x.sentAt=c.now();c.save('أصبح قيد النقل');c.render()});
 document.querySelectorAll('[data-receive-transfer]').forEach(b=>b.onclick=()=>{const x=c.db.transferOrders.find(t=>t.id===b.dataset.receiveTransfer);if(!x)return;c.db.stockMoves.push({id:c.uid('sm'),companyId:x.companyId,warehouseId:x.to,productId:x.productId,type:'receipt',qty:x.qty,date:c.today(),ref:x.number,note:'استلام تحويل'});x.status='received';x.receivedAt=c.now();c.save('تم الاستلام');c.render()});
 document.querySelector('#bulkCount')?.addEventListener('click',()=>{c.openModal('جرد جماعي',bulkForm(c),true);setTimeout(()=>{const f=document.querySelector('#bulkCountForm');if(f)f.onsubmit=e=>{e.preventDefault();const wid=new FormData(f).get('warehouseId'),lines=[];f.querySelectorAll('tbody tr').forEach(tr=>{const input=tr.querySelector('.actual');if(input.value==='')return;const pid=tr.dataset.pid,before=c.stock(pid,wid),actual=n(input.value),diff=actual-before;if(diff)c.db.stockMoves.push({id:c.uid('sm'),companyId:c.db.session.companyId,warehouseId:wid,productId:pid,type:diff>0?'receipt':'out',qty:Math.abs(diff),date:c.today(),ref:'BULK-COUNT',note:'جرد جماعي'});lines.push({productId:pid,before,actual,diff})});c.db.bulkCounts.unshift({id:c.uid('bc'),warehouseId:wid,date:c.today(),lines,createdAt:c.now()});c.save('تمت تسوية '+lines.length+' منتج');c.closeModal();c.render()}},0)})
}

function couponDiscount(c,code,total){const x=c.db.coupons.find(v=>v.code.toLowerCase()===String(code||'').trim().toLowerCase()&&v.active!==false&&(!v.until||v.until>=c.today()));if(!x||n(x.minTotal)>total)return 0;return x.type==='percent'?Math.min(total,total*n(x.value)/100):Math.min(total,n(x.value))}
function viewPOS(c){let html=NBADV.viewPOS(c),m='<div class="pos-actions">',x=`<div class="pos-final-tools"><div class="field"><label>كوبون</label><input id="posCoupon" value="${c.esc(c.db.ui.posCoupon||'')}"></div><button class="btn outline" id="posFullscreen">ملء الشاشة</button><button class="btn outline" id="posExchange">استبدال</button><button class="btn outline" id="thermalLast">80mm</button></div>`;return html.includes(m)?html.replace(m,x+m):html+x}
function wirePOS(c){
 NBADV.wirePOS(c);
 document.querySelector('#posCoupon')?.addEventListener('change',e=>{const base=c.state.posCart.reduce((s,x)=>s+n(x.qty)*n(x.price),0),disc=couponDiscount(c,e.target.value,base);c.db.ui.posCoupon=e.target.value;c.db.ui.posDiscount=disc;c.save(disc?'تم تطبيق الكوبون':'الكوبون غير صالح');c.render()});
 document.querySelector('#posFullscreen')?.addEventListener('click',()=>document.querySelector('.main')?.requestFullscreen?.().catch(()=>c.toast('غير مدعوم')));
 document.querySelector('#thermalLast')?.addEventListener('click',()=>{const i=c.db.invoices.filter(x=>x.shiftId&&!x.deletedAt).slice(-1)[0];i?printThermal(c,i):c.toast('لا توجد فاتورة POS')});
 document.querySelector('#posExchange')?.addEventListener('click',()=>exchange(c))
}
function exchange(c){const no=prompt('رقم الفاتورة الأصلية');if(!no)return;const i=c.db.invoices.find(x=>x.number===no&&!x.deletedAt);if(!i)return c.toast('الفاتورة غير موجودة');const a=prompt('SKU المنتج المرجع'),b=prompt('SKU المنتج البديل'),p1=c.db.products.find(p=>p.sku===a),p2=c.db.products.find(p=>p.sku===b);if(!p1||!p2)return c.toast('تحقق من SKU');const line=i.items.find(x=>x.productId===p1.id);if(!line)return c.toast('المنتج غير موجود بالفاتورة');if(NBADV.availableStock(c,p2.id,i.warehouseId)<1)return c.toast('البديل غير متوفر');const d=n(p2.price)-n(line.price);c.db.stockMoves.push({id:c.uid('sm'),companyId:i.companyId,warehouseId:i.warehouseId,productId:p1.id,type:'receipt',qty:1,date:c.today(),ref:'EX-'+i.number,note:'استبدال'},{id:c.uid('sm'),companyId:i.companyId,warehouseId:i.warehouseId,productId:p2.id,type:'delivery',qty:1,date:c.today(),ref:'EX-'+i.number,note:'استبدال'});c.db.exchanges.unshift({id:c.uid('ex'),invoiceId:i.id,fromProductId:p1.id,toProductId:p2.id,delta:d,date:c.today()});if(d)c.db.cashTransactions.push({id:c.uid('ct'),companyId:i.companyId,accountId:c.db.cashAccounts[0]?.id,date:c.today(),type:d>0?'in':'out',amount:Math.abs(d),ref:'EX-'+i.number,note:'فرق استبدال',createdAt:c.now()});c.save('تم الاستبدال');c.render()}
function printThermal(c,i){const t=c.invTotals(i),w=window.open('','_blank');if(!w)return c.toast('اسمح بالنوافذ المنبثقة');w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><style>@page{size:80mm auto;margin:2mm}body{width:76mm;font-family:Arial;font-size:11px;text-align:center}.r{display:flex;justify-content:space-between;border-bottom:1px dashed #aaa;padding:5px 0}.total{font-size:15px;font-weight:bold;margin:8px}</style></head><body><h2>${c.esc(c.company().name)}</h2><div>${c.esc(i.number)} • ${i.date}</div><hr>${i.items.map(x=>`<div class="r"><span>${c.esc(x.name)} × ${x.qty}</span><b>${c.fmt(n(x.qty)*n(x.price))}</b></div>`).join('')}<div class="total">${c.fmt(t.total)}</div><div>مدفوع ${c.fmt(t.paid)} | متبقي ${c.fmt(t.due)}</div><script>onload=()=>print()<\/script></body></html>`);w.document.close()}

function viewPurchasing(c){
 const base=NBHYPER.viewPurchasing(c),pr=c.db.purchaseRequests.filter(x=>x.companyId===c.db.session.companyId),rfq=c.db.rfqs.filter(x=>x.companyId===c.db.session.companyId),vb=c.db.vendorBills.filter(x=>x.companyId===c.db.session.companyId);
 return base+`<div class="pr-grid3"><section class="card"><div class="card-head"><h3>Purchase Request</h3><button class="btn sm" id="newPR">＋ طلب</button></div>${pr.slice(-8).reverse().map(x=>`<div class="stat-row"><div class="grow"><strong>${c.esc(x.number)}</strong><div class="sub">${c.esc(x.status)} • ${x.qty}</div></div><button class="btn sm" data-pr-rfq="${x.id}">RFQ</button></div>`).join('')||'<div class="empty">لا توجد طلبات</div>'}</section><section class="card"><div class="card-head"><h3>RFQ / مقارنة</h3></div>${rfq.slice(-8).reverse().map(x=>`<div class="stat-row"><div class="grow"><strong>${c.esc(x.number)}</strong><div class="sub">${(x.offers||[]).length} عرض</div></div><button class="btn sm" data-rfq="${x.id}">فتح</button></div>`).join('')||'<div class="empty">لا توجد RFQ</div>'}</section><section class="card"><div class="card-head"><h3>Vendor Bills</h3><button class="btn sm" id="newVB">＋ فاتورة</button></div>${vb.slice(-8).reverse().map(x=>`<div class="stat-row"><div class="grow"><strong>${c.esc(x.number)}</strong><div class="sub">${c.esc(c.db.suppliers.find(s=>s.id===x.supplierId)?.name||'')} • ${c.esc(x.status)}</div></div><strong>${c.fmt(x.total)}</strong></div>`).join('')||'<div class="empty">لا توجد فواتير</div>'}</section></div>`;
}
function prForm(c){return `<form id="prForm"><div class="form-grid"><div class="field"><label>المنتج</label><select name="productId">${c.db.products.filter(p=>p.active).map(p=>`<option value="${p.id}">${c.esc(p.nameAr)}</option>`).join('')}</select></div><div class="field"><label>الكمية</label><input name="qty" type="number" min=".01" required></div><div class="field"><label>مطلوب قبل</label><input name="neededBy" type="date"></div><div class="field full"><label>السبب</label><input name="reason"></div></div><div class="toolbar"><button class="btn primary">إنشاء</button><button class="btn" type="button" data-close>إلغاء</button></div></form>`}
function vbForm(c){return `<form id="vbForm"><div class="form-grid"><div class="field"><label>المورد</label><select name="supplierId">${c.db.suppliers.map(s=>`<option value="${s.id}">${c.esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>PO</label><select name="poId"><option value="">—</option>${c.db.purchaseOrders.filter(p=>['received','closed'].includes(p.status)).map(p=>`<option value="${p.id}">${c.esc(p.number)}</option>`).join('')}</select></div><div class="field"><label>رقم المورد</label><input name="externalNo"></div><div class="field"><label>الاستحقاق</label><input name="dueDate" type="date"></div><div class="field"><label>الإجمالي</label><input name="total" type="number" min="0" required></div></div><div class="toolbar"><button class="btn primary">حفظ</button><button class="btn" type="button" data-close>إلغاء</button></div></form>`}
function wirePurchasing(c){
 NBHYPER.wirePurchasing(c);
 document.querySelector('#newPR')?.addEventListener('click',()=>{c.openModal('طلب شراء داخلي',prForm(c),false);setTimeout(()=>{const f=document.querySelector('#prForm');if(f)f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),x={id:c.uid('pr'),companyId:c.db.session.companyId,number:uniq('PR',c.db.purchaseRequests),requester:c.currentUser().name,productId:fd.get('productId'),qty:n(fd.get('qty')),neededBy:fd.get('neededBy'),reason:fd.get('reason'),status:'pending',createdAt:c.now()};c.db.purchaseRequests.unshift(x);c.save('تم إنشاء '+x.number);c.closeModal();c.render()}},0)});
 document.querySelectorAll('[data-pr-rfq]').forEach(b=>b.onclick=()=>{const p=c.db.purchaseRequests.find(x=>x.id===b.dataset.prRfq);if(!p)return;const x={id:c.uid('rfq'),companyId:p.companyId,number:uniq('RFQ',c.db.rfqs),requestId:p.id,productId:p.productId,qty:p.qty,offers:[],status:'open',createdAt:c.now()};c.db.rfqs.unshift(x);p.status='rfq';c.save('تم إنشاء '+x.number);c.render()});
 document.querySelectorAll('[data-rfq]').forEach(b=>b.onclick=()=>openRFQ(c,b.dataset.rfq));
 document.querySelector('#newVB')?.addEventListener('click',()=>{c.openModal('فاتورة مورد',vbForm(c),false);setTimeout(()=>{const f=document.querySelector('#vbForm');if(f)f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),x={id:c.uid('vb'),companyId:c.db.session.companyId,number:uniq('VB',c.db.vendorBills),supplierId:fd.get('supplierId'),purchaseOrderId:fd.get('poId'),externalNo:fd.get('externalNo'),date:c.today(),dueDate:fd.get('dueDate'),total:n(fd.get('total')),paid:0,status:'open',createdAt:c.now()};c.db.vendorBills.unshift(x);c.save('تم حفظ '+x.number);c.closeModal();c.render()}},0)})
}
function openRFQ(c,id){const x=c.db.rfqs.find(r=>r.id===id);if(!x)return;c.openModal('مقارنة '+x.number,`<div class="card-head"><h3>${c.esc(prod(c,x.productId)?.nameAr||'')} × ${x.qty}</h3><button class="btn sm" id="addOffer">＋ عرض</button></div>${(x.offers||[]).map(o=>`<div class="stat-row"><div class="grow"><strong>${c.esc(c.db.suppliers.find(s=>s.id===o.supplierId)?.name||'')}</strong><div class="sub">${o.days} يوم</div></div><strong>${c.fmt(o.unitCost)}</strong><button class="btn sm green" data-award="${o.id}">اختيار</button></div>`).join('')||'<div class="empty">لا عروض</div>'}`,true);setTimeout(()=>{document.querySelector('#addOffer')?.addEventListener('click',()=>{const sid=prompt('ID المورد');if(!c.db.suppliers.find(s=>s.id===sid))return c.toast('المورد غير موجود');const cost=n(prompt('سعر الوحدة','0')),days=n(prompt('مدة التوريد','1'));x.offers.push({id:c.uid('off'),supplierId:sid,unitCost:cost,days});c.db.supplierPriceHistory.unshift({id:c.uid('sph'),supplierId:sid,productId:x.productId,cost,date:c.today(),source:x.number});c.save();c.closeModal();openRFQ(c,id)});document.querySelectorAll('[data-award]').forEach(b=>b.onclick=()=>award(c,x,b.dataset.award))},0)}
function award(c,r,id){const o=r.offers.find(x=>x.id===id);if(!o)return;const po={id:c.uid('po'),companyId:c.db.session.companyId,branchId:c.db.session.branchId,warehouseId:c.warehouse()?.id||'',number:uniq('PO',c.db.purchaseOrders),date:c.today(),supplierId:o.supplierId,status:'approved',items:[{productId:r.productId,qty:r.qty,cost:o.unitCost}],notes:'من '+r.number,receivedQty:0,receivedByProduct:{},payments:[],createdAt:c.now()};c.db.purchaseOrders.unshift(po);r.status='awarded';const p=c.db.purchaseRequests.find(x=>x.id===r.requestId);if(p)p.status='ordered';c.save('تم إنشاء '+po.number);c.closeModal();c.render()}

function journals(c){return [...(c.db.journals||[]),...(NBHYPER.autoJournals?NBHYPER.autoJournals(c):[])]}
function viewAccounting(c){
 const base=NBHYPER.viewAccounting(c);
 return base+`<div class="pr-grid2"><section class="card"><div class="card-head"><h3>General Ledger</h3><button class="btn sm" id="openLedger">فتح</button></div><div class="card-head"><h3>Opening Balances</h3><button class="btn sm" id="newOpening">＋ رصيد</button></div>${c.db.openingBalances.slice(-8).map(x=>`<div class="stat-row"><span>${c.esc(c.db.accounts.find(a=>a.id===x.accountId)?.name||'')}</span><strong>${c.fmt(x.debit-x.credit)}</strong></div>`).join('')||'<div class="empty">لا توجد أرصدة</div>'}</section><section class="card"><div class="card-head"><h3>الفترات المالية</h3><button class="btn sm" id="closePeriod">إقفال</button></div>${c.db.fiscalPeriods.slice(0,12).map(x=>`<div class="stat-row"><strong>${c.esc(x.name)}</strong><div class="grow"></div><span class="badge ${x.status==='open'?'green':'gray'}">${c.esc(x.status)}</span></div>`).join('')}<div class="card-head"><h3>مراكز التكلفة</h3><button class="btn sm" id="newCC">＋ مركز</button></div>${c.db.costCenters.map(x=>`<div class="stat-row"><strong>${c.esc(x.code)}</strong><div class="grow">${c.esc(x.name)}</div></div>`).join('')||'<div class="empty">لا توجد مراكز</div>'}</section></div>`;
}
function wireAccounting(c){
 document.querySelector('#openLedger')?.addEventListener('click',()=>{const code=prompt('كود الحساب'),a=c.db.accounts.find(x=>x.code===code);if(!a)return c.toast('الحساب غير موجود');let bal=0,rows=[];journals(c).forEach(j=>(j.lines||[]).forEach(l=>{if(l.accountId===a.id)rows.push({date:j.date,no:j.number,memo:j.memo,d:n(l.debit),cr:n(l.credit)})}));rows.sort((x,y)=>String(x.date).localeCompare(String(y.date)));c.openModal('دفتر الأستاذ — '+a.name,`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>المرجع</th><th>البيان</th><th>مدين</th><th>دائن</th><th>الرصيد</th></tr></thead><tbody>${rows.map(x=>{bal+=x.d-x.cr;return`<tr><td>${x.date}</td><td>${c.esc(x.no)}</td><td>${c.esc(x.memo||'')}</td><td>${c.fmt(x.d)}</td><td>${c.fmt(x.cr)}</td><td>${c.fmt(bal)}</td></tr>`}).join('')}</tbody></table></div>`,true)});
 document.querySelector('#newOpening')?.addEventListener('click',()=>{const code=prompt('كود الحساب'),a=c.db.accounts.find(x=>x.code===code);if(!a)return c.toast('الحساب غير موجود');const v=n(prompt('موجب = مدين، سالب = دائن','0')),eq=c.db.accounts.find(x=>x.code==='3100');c.db.openingBalances.push({id:c.uid('ob'),accountId:a.id,date:c.today(),debit:v>0?v:0,credit:v<0?Math.abs(v):0});c.db.journals.push({id:c.uid('je'),number:uniq('OPEN',c.db.journals),date:c.today(),memo:'رصيد افتتاحي '+a.name,lines:[{accountId:a.id,debit:v>0?v:0,credit:v<0?Math.abs(v):0},{accountId:eq.id,debit:v<0?Math.abs(v):0,credit:v>0?v:0}]});c.save('تم حفظ الرصيد');c.render()});
 document.querySelector('#newCC')?.addEventListener('click',()=>{const code=prompt('الكود'),name=prompt('الاسم');if(!code||!name)return;c.db.costCenters.push({id:c.uid('cc'),code,name,active:true});c.save('تمت الإضافة');c.render()});
 document.querySelector('#closePeriod')?.addEventListener('click',()=>{const key=prompt('الفترة YYYY-MM',c.today().slice(0,7)),p=c.db.fiscalPeriods.find(x=>x.name===key);if(!p)return c.toast('الفترة غير موجودة');p.status='closed';c.db.security.lockDate=p.to;c.save('تم إقفال '+key);c.render()})
}

function viewDocuments(c){return NBHYPER.viewDocuments(c)+`<div class="pr-doc-tools"><button class="btn outline" id="docReceipt">سند قبض</button><button class="btn outline" id="docPayment">سند صرف</button><button class="btn outline" id="docStatement">كشف حساب</button><button class="btn outline" id="docSalary">كشف راتب</button><button class="btn outline" id="docThermal">80mm</button></div><div class="card"><div class="card-head"><h3>قوالب NovaBlu</h3></div><div class="pr-doc-status"><span>A4 <b>جاهز</b></span><span>Thermal <b>جاهز</b></span><span>هوية الشركة <b>فعالة</b></span><span>Reference/QR <b>جاهز للربط</b></span></div></div>`}
function simpleDoc(c,title,rows,ref=''){const w=window.open('','_blank');if(!w)return c.toast('اسمح بالنوافذ المنبثقة');w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><style>@page{size:A4;margin:12mm}body{font-family:Arial}.h{display:flex;justify-content:space-between;border-bottom:3px solid #2563eb}.r{display:flex;justify-content:space-between;padding:10px;border-bottom:1px solid #eee}.b{border:1px solid #ddd;border-radius:10px;padding:14px;margin-top:20px}</style></head><body><div class="h"><h2>${c.esc(c.company().name)}</h2><div><h2>${c.esc(title)}</h2><strong>${c.esc(ref)}</strong></div></div><div class="b">${rows.map(x=>`<div class="r"><span>${c.esc(x[0])}</span><strong>${c.esc(String(x[1]??''))}</strong></div>`).join('')}</div><script>onload=()=>print()<\/script></body></html>`);w.document.close()}
function wireDocuments(c){
 document.querySelector('#docReceipt')?.addEventListener('click',()=>{const v=prompt('المبلغ'),x=prompt('استلمنا من');if(v)simpleDoc(c,'سند قبض',[['استلمنا من',x],['المبلغ',c.fmt(n(v))],['التاريخ',c.today()]],uniq('RCV',c.db.cashTransactions))});
 document.querySelector('#docPayment')?.addEventListener('click',()=>{const v=prompt('المبلغ'),x=prompt('دفعنا إلى');if(v)simpleDoc(c,'سند صرف',[['دفعنا إلى',x],['المبلغ',c.fmt(n(v))],['التاريخ',c.today()]],uniq('PAY',c.db.cashTransactions))});
 document.querySelector('#docStatement')?.addEventListener('click',()=>{const q=prompt('اسم أو هاتف العميل'),u=c.db.customers.find(x=>x.name===q||x.phone===q);if(!u)return c.toast('غير موجود');const a=c.db.invoices.filter(i=>i.customerId===u.id&&!i.deletedAt),tot=a.reduce((s,i)=>s+c.invTotals(i).total,0),paid=a.reduce((s,i)=>s+c.invTotals(i).paid,0);simpleDoc(c,'كشف حساب',[['العميل',u.name],['الإجمالي',c.fmt(tot)],['المدفوع',c.fmt(paid)],['المتبقي',c.fmt(tot-paid)]],u.phone)});
 document.querySelector('#docSalary')?.addEventListener('click',()=>{const id=prompt('ID الموظف'),e=c.db.employees.find(x=>x.id===id);e?simpleDoc(c,'كشف راتب',[['الموظف',e.name],['الوظيفة',e.jobTitle||''],['الراتب',c.fmt(e.salary||0)],['الفترة',c.today().slice(0,7)]],id):c.toast('غير موجود')});
 document.querySelector('#docThermal')?.addEventListener('click',()=>{const no=prompt('رقم الفاتورة'),i=c.db.invoices.find(x=>x.number===no&&!x.deletedAt);i?printThermal(c,i):c.toast('غير موجود')})
}

function idbOpen(){return new Promise((ok,no)=>{const r=indexedDB.open('NovaBluERP2',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('state'))d.createObjectStore('state',{keyPath:'key'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function persist(c){if(!('indexedDB'in window))return false;try{const d=await idbOpen(),t=d.transaction('state','readwrite');t.objectStore('state').put({key:'current',savedAt:Date.now(),data:c.clone(c.db)});return await new Promise(r=>{t.oncomplete=()=>{d.close();r(true)};t.onerror=()=>r(false)})}catch{return false}}
async function state(){if(!('indexedDB'in window))return null;try{const d=await idbOpen(),t=d.transaction('state','readonly'),g=t.objectStore('state').get('current');return await new Promise(r=>{g.onsuccess=()=>{d.close();r(g.result||null)};g.onerror=()=>r(null)})}catch{return null}}
function viewData(c){return NBHYPER.viewData(c)+`<div class="pr-grid2"><section class="card"><div class="card-head"><h3>Performance & Recovery</h3></div><div class="statement-row"><span>LocalStorage</span><strong>Fallback</strong></div><div class="statement-row"><span>IndexedDB</span><strong class="good-text">Dual Write</strong></div><div class="toolbar"><button class="btn outline" id="idbSync">مزامنة</button><button class="btn outline" id="idbCheck">فحص Recovery</button></div></section><section class="card"><div class="card-head"><h3>Import Wizard</h3><button class="btn sm" id="undoImport">Undo Import</button></div><input type="file" id="wizardCsv" accept=".csv,text/csv"><div id="wizardPreview" class="sub">Preview + Mapping + Duplicate Guard</div></section></div>`}
function parseCsv(s){const rows=[];let row=[],cell='',q=false;for(let i=0;i<s.length;i++){const ch=s[i],nx=s[i+1];if(ch==='"'){if(q&&nx==='"'){cell+='"';i++}else q=!q}else if(ch===','&&!q){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(Boolean))rows.push(row);return rows}
function wireData(c){
 NBHYPER.wireData(c);NBADV.wireDataExtras?.(c);
 document.querySelector('#idbSync')?.addEventListener('click',async()=>c.toast(await persist(c)?'تمت المزامنة':'تعذر الحفظ'));
 document.querySelector('#idbCheck')?.addEventListener('click',async()=>{const x=await state();c.toast(x?'آخر نسخة '+new Date(x.savedAt).toLocaleString('ar-IQ'):'لا توجد نسخة')});
 document.querySelector('#wizardCsv')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>wizard(c,parseCsv(r.result));r.readAsText(f)});
 document.querySelector('#undoImport')?.addEventListener('click',()=>{const j=c.db.importJobs[0];if(!j||j.undone)return c.toast('لا يوجد استيراد قابل للتراجع');if(j.type==='products')c.db.products=c.db.products.filter(x=>!j.ids.includes(x.id));else c.db.customers=c.db.customers.filter(x=>!j.ids.includes(x.id));j.undone=true;c.save('تم Undo');c.render()})
}
function wizard(c,rows){if(rows.length<2)return c.toast('الملف فارغ');const h=rows[0],host=document.querySelector('#wizardPreview');host.innerHTML=`<div class="table-wrap"><table><tbody>${rows.slice(0,6).map(r=>`<tr>${r.map(v=>`<td>${c.esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="form-grid"><div class="field"><label>النوع</label><select id="wizType"><option value="products">منتجات</option><option value="customers">عملاء</option></select></div><div class="field"><label>عمود الاسم</label><select id="wizName">${h.map((x,i)=>`<option value="${i}">${c.esc(x)}</option>`).join('')}</select></div><div class="field"><label>عمود SKU/Phone</label><select id="wizKey">${h.map((x,i)=>`<option value="${i}">${c.esc(x)}</option>`).join('')}</select></div></div><button class="btn primary" id="wizRun">استيراد ${rows.length-1}</button>`;document.querySelector('#wizRun').onclick=()=>{const type=document.querySelector('#wizType').value,ni=n(document.querySelector('#wizName').value),ki=n(document.querySelector('#wizKey').value),ids=[];rows.slice(1).forEach(r=>{if(!r[ni])return;if(type==='products'){const key=String(r[ki]||'').trim();if(key&&c.db.products.some(p=>p.sku===key))return;const id=c.uid('p');c.db.products.push({id,companyId:c.db.session.companyId,nameAr:r[ni],nameEn:'',sku:key||'IMP-'+id.slice(-5),barcode:'',categoryId:'',unit:'قطعة',baseUom:'قطعة',uoms:['قطعة'],cost:0,price:0,tax:0,trackStock:true,reorder:0,active:true});ids.push(id)}else{const key=String(r[ki]||'').trim();if(key&&c.db.customers.some(x=>x.phone===key))return;const id=c.uid('c');c.db.customers.push({id,companyId:c.db.session.companyId,name:r[ni],phone:key,email:'',address:'',taxId:'',notes:'',creditLimit:0,createdAt:c.now()});ids.push(id)}});c.db.importJobs.unshift({id:c.uid('imp'),type,ids,at:c.now(),undone:false});c.save('تم استيراد '+ids.length);c.render()}}

function runtime(c){const a=[],add=(x,ok,d='')=>a.push({x,ok,d});['NBPRO','NBINVOICE','NBHYPER','NBADV','NBUX','NBRELEASE'].forEach(x=>add(x,!!window[x],!!window[x]?'Loaded':'Missing'));add('IndexedDB','indexedDB'in window,navigator.userAgent);add('Service Worker',!!navigator.serviceWorker);add('Print',typeof window.print==='function');add('Database',!!c.db.meta&&Array.isArray(c.db.products));const nums=c.db.invoices.filter(i=>!i.deletedAt).map(i=>i.number);add('Invoice uniqueness',new Set(nums).size===nums.length);add('Warehouses',!!c.warehouse());return a}
function viewQA(c){const base=NBUX.viewQA(c),r=runtime(c),ok=r.filter(x=>x.ok).length;return base+`<div class="card"><div class="card-head"><h3>Pre‑Release Runtime</h3><span class="badge ${ok===r.length?'green':'amber'}">${ok}/${r.length}</span></div><div class="pr-runtime">${r.map(x=>`<div class="${x.ok?'pass':'fail'}"><span>${c.icon(x.ok?'check':'notifications',17)}</span><div><strong>${c.esc(x.x)}</strong><small>${c.esc(x.d)}</small></div></div>`).join('')}</div><div class="notice">اختبارات تعدد الأجهزة، الضغط، الاختراق والمزامنة الفعلية تبقى ضمن الربط السحابي النهائي.</div></div>`}
function wireQA(c){NBUX.wireQA(c)}
function init(c){migrate(c);persist(c)}
window.NBRELEASE={migrate,init,persist,viewProducts,wireProducts,viewInventory,wireInventory,viewPOS,wirePOS,viewPurchasing,wirePurchasing,viewAccounting,wireAccounting,viewDocuments,wireDocuments,viewData,wireData,viewQA,wireQA,printThermal,runtime,uomFactor,variants,inTransit};
})();
